[package]
name = "hmac-procs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1", features = ["full"] }
quote = "*"
proc-macro2 = "*"
lazy_static = "*"

[lib]
proc-macro = true